#!/bin/bash

set -e

user=test
from_name='Test'
from_email=$1
to_name='Tu nombre'
to_email=$2
file=/tmp/emailtest.eml

if [ -z "$from_email" ] || [ -z "$to_email" ]; then
    echo "Usage: $(basename $0) <email_from> <email_to>"
    exit 1
fi

echo -n "Preparando email ... "
cat > $file << EOL
Subject: Prueba de email para $HOST.$DOMAIN
From: $from_name <$from_email>
To: $to_name <$to_email>
Content-Type: text/plain; charset=UTF-8

Este es un correo electrónico de prueba para el servidor $HOST.$DOMAIN.
No tiene que hacer nada, pero quítelo.
Gracias

EOL
echo "OK"

echo -n "Enviando email using sendmail ... "
sendmail -f "$from_email" "$to_email" < $file
error=$?; if [ $error -ne 0 ]; then echo "ERROR: $error"; exit $error; fi
echo "OK"

echo -n "Esperando unos segundos ... "
sleep 5
echo "OK"

echo "-----------------------------------------------------"
echo " Log"
echo "-----------------------------------------------------"
tail /var/log/syslog

echo "-----------------------------------------------------"
echo " Cola de correo saliente"
echo "-----------------------------------------------------"
postqueue -p
